branches: [master]
plugins:
  - "@semantic-release/commit-analyzer"
  - - "@semantic-release/release-notes-generator"
    - linkCompare: false
      linkReferences: false
  - - "@semantic-release/npm"
    - npmPublish: false
  - - "@semantic-release/exec"
    - prepareCmd: 'echo "${nextRelease.notes}" > app/src/main/play/release-notes/en-US/beta.txt'
      publishCmd: "./.github/scripts/publish-to-play-store.sh ${nextRelease.version}"
  - "@semantic-release/github"
