branch: release-automation
extends: "@relaycorp/shared-config"
plugins:
  - - "@semantic-release/npm"
    - npmPublish: false
  - - "@semantic-release/exec"
    - prepareCmd: "echo ${nextRelease.notes} > src/main/play/release-notes/en-US/default.txt"
      publishCmd: './gradlew publish -PversionName=${nextRelease.version} -PgcpServiceAccountCredentials=/tmp/gpc-service-account.json'
