name: "Validate PR title"
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: action-semantic-pull-request
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
